### ISSUE TITLE
GltfImporter: spot light with outer angle of 90° produces error

### ISSUE THREAD

**Issue by pezcode** [mosra/magnum-plugins#139]
KHR_lights_punctual [states](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_lights_punctual/README.md#spot):

> outerConeAngle | Must be greater than innerConeAngle and less than or equal to PI / 2.0

So 90° should be allowed 🙇 

Relevant code is here: https://github.com/mosra/magnum-plugins/blob/8e5cf7ac9820be5cf1f8728db83a284eb9120090/src/MagnumPlugins/GltfImporter/GltfImporter.cpp#L2160

**Comment by mosra** [comment]
Thanks, yes this is obviously a bug on my side. Though I wonder if changing from `>` to `>=` will actually fix it due to the imprecisions happening when converting from degrees to radians, or from 64-bit doubles to floats...

I'll look into this as soon as I can think straight again, got some nasty cold this week.

**Comment by pezcode** [comment]
> the imprecisions

Maybe just warning (and possibly clamping) is a safer solution.

Anyway, there's no rush. Get well soon🙏

**Comment by mosra** [comment]
Fixed in c39f2c595c49023dfdf0c552d82abcfaefa09b1e. I expected some nasty floating-point issues but it seems to "just work" also with a double-precision representation of 90°, so yay.

**Comment by pezcode** [comment]
Thank you 😊
