### ISSUE TITLE
OtherImageImporter type and fallback loading

### ISSUE THREAD

**Issue by ghost** [mosra/magnum-plugins#25]
DevIL can load a lot of formats that aren't super common (so I've declined to add an explicit loader type for all possible configurations) as well as ones that pre-exist extensions or have no common extension type. Perhaps we could have an `OtherImageImporter` type of plugin, that would attempt to load images that there is no current explicit support for?

As well, what happens if more than one plugin supports, for example, `JpegImporter`? How is one selected? I don't see any sort of system for priority or fail over loading, so if StbImageImporter fails to load a type that DevilImageImporter could have easily loaded (such as a complex PNG or something), that seems like a sign some sort of fail over or fall back logic is warranted.

**Comment by mosra** [comment]
There's a TODO in the `AnyImageImporter` code that mentions ability to detect file type based on first few bytes of the file. I didn't get around to do that yet, but that may help with files that have no common extension. As long as an image type is publicly documented and has some extension and/or is detectable from file prefix, I would not hesitate with creating an importer alias for it.

*(Note that I didn't look in the DevIL PR yet, so I might be talking irrelevant bullshit here. Sorry in that case.)*

Crazy thinking -- what would aliasing `DevilImageImporter` to `AnyImageImporter` mean? Would it make sense? In some case?

Regarding `OtherImageImporter` -- for this to work there would need to be some fallback mechanism like you suggest, testing all possible importers until some of them is able to open the image. That's not there and I'm not sure if I should put it in -- some corrupt or funny files might crash some implementations and just going through all of them doesn't seem like a good idea. At least until we can fuzz all the plugins and all dependencies of all the plugins and fix all the crashes :) This should be done rather on the application side (it *is* possible to list all possible alias candidates through PluginManager metadata APIs). In this case if `DevilImageImporter` (and others) would be aliased to `AnyImageImporter`, an app could just go through all `AnyImageImporter`s until some of them happily provides the data. Then one would also not need to implement any format detection based on magic in file headers in the original `AnyImageImporter` if DevIL is able to handle that by itself.

Priorities -- I wanted to make the plugins as independent from each other as possible, so there is no priority or hierarchy of them. Worst of all it's often dependent on the actual use case -- sometimes the users might prefer custom code from DevIL because their system has only vanilla libjpeg that is slow but in the other case they would want to prefer libjpeg-turbo because DevIL doesn't support 12bit YCCK JPEGs or something. Currently the plugin manager just does "first come, first serve" -- if there is a plugin with that name, it's used, otherwise it just uses first plugin with that alias that it finds, nothing more. I think this should be user-controllable instead of putting some logic to the plugin manager. A few options that come to my mind:

- Adding an API to the plugin manager that allows one to say which plugin should be preferred when loading e.g. `JpegImporter`. Internally it would then check (assert) that such plugin exists, is loadable and does actually provide given alias and then it would update the mapping table. For example

    ```cpp
    manager.setAlias("JpegImporter", "DevilImageImporter");
    ```
- Or just preferring already loaded plugins when searching for aliases. That would make it foolproof (no asserts if someone "holds it wrong") but on the other hand depending too much on random app behavior (if someone part of the code loads a plugin, it could affect selection of a plugin somewhere else).

    ```cpp
    // Load the plugin to prefer that implementation for *all* aliases that the plugin 
    // registers (it already sounds wrong, right?)
    manager.load("DevilImageImporter");
    ```

**Comment by mosra** [comment]
There's the `PluginManager::Manager::setPreferredPlugins()` API which fits the first described case, since mosra/corrade@ea40e0d2e576688da6567994e50fa25c80933196. *(Huh, it took me a year and half? :see_no_evil: )*

Any*Importer detection of file type from file data instead of extension is tracked elsewhere, so I guess I'll close this :)
