### ISSUE TITLE
miss reference over libjpeg include folder name.

### ISSUE THREAD

**Issue by hunt978** [mosra/magnum-plugins#51]
https://github.com/mosra/magnum-plugins/blob/9c81cdc0b38251a1471f4d9a9f2acae99f43d872/src/MagnumPlugins/JpegImageConverter/CMakeLists.txt#L51

may should be the ```${JPEG_INCLUDE_DIR}``` without the *S*.

**Comment by mosra** [comment]
Oh, you're right, sorry about that. For some reason the CMake [FindJPEG](https://cmake.org/cmake/help/latest/module/FindJPEG.html) module didn't follow the common naming scheme and this wasn't corrected until version 3.12.

Fixed in d0b3385815be8442f945b3c55272efce8c8f24ab. Thanks a lot for reporting this! :+1:
