### ISSUE TITLE
Expose Configuration Value implementation for Trade::BasisImporter::TargetFormat

### ISSUE THREAD

**Issue by Squareys** [mosra/magnum-plugins#93]
Hi @mosra !

As TargetFormat is a public enum, it would make sense to also expose the ConfigurationValue conversion for it to allow `configuration().value<TargetFormat>()` to be used outside of the internal importer code:
https://github.com/mosra/magnum-plugins/blob/2e7d90c88f7335448a9a8111678de7146fd81bc9/src/MagnumPlugins/BasisImporter/BasisImporter.cpp#L98-L120

In case I find some time, I might do this, but until then, here for anyone to pick up.

Best,
Jonathan

**Comment by mosra** [comment]
Wait, for what do you need the enum, actually? Assuming the plugin is instantiated through the manager as recommended, there enum is not accessible anyway.

And if you want to call `setTargetFormat()`, but with a string, do `configuration().setValue("format", theFormatString)`, as usual with any other plugin-specific configuration :)

**Comment by Squareys** [comment]
In this case I have a global config setting the target format before the Importer is instanced. As I also allocate a GPU Texture upfront, I need to know the CompressedPixelFormat that is going to get imported.

To get that without the plugin instance I currently copied both the `compressedPixelFormat()` and Configuration implementation into my code 😅 Ideally I could use the same code as BasisImporter function for that, as this wouldn't get updated with the plugin, hence harder to maintain.

I suppose, I could also hard-code the CompressedPixelFormat when setting the TargetFormat via String (ideally, this could throw compile-time errors, though, using the Configuration implementation in case formats get removed, like after switching to the USTC update)

**Comment by mosra** [comment]
But .... this seems kinda roundabout and harder than it should be (apologies in advance if any harsh/annoyed language leaks through due to my *really bad day*).

> I also allocate a GPU Texture upfront, I need to know the CompressedPixelFormat that is going to get imported.

Yes. So you iterate through available extensions and pick the best one that is supported. Like shown [in the BasisImporter docs](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1BasisImporter.html#Trade-BasisImporter-target-format). When you pick a certain extension, you also know what format it provides and the Basis format name is then *derived from that* (and not the other way around). So for example

```cpp
    CompressedPixelFormat format;
    ...
    } else if(context.isExtensionSupported<EXT::texture_compression_s3tc>()) {
        format = CompressedPixelFormat::Bc3RGBAUnorm;
        metadata->configuration().setValue("format", "Bc3RGBA");
    } else if(context.isExtensionSupported<ARB::ES3_compatibility>()) {
        format = CompressedPixelFormat::Etc2RGBAUnorm;
        metadata->configuration().setValue("format", "Etc2RGBA");
    } ...
```

I don't think this counts as code duplication because you *have* to do this GL-dialect-specific branching in any case anyway (and the plugin can't do that for you because it's independent of the GL library by design). And it's technically not possible for `Etc2` to be updated to mean some other compression that'd be suddenly incompatible with `Etc2RGBAUnorm`.

And as is common with Magnum, any future update will preserve original names, give you concrete deprecation messages to act upon and enough time to switch over the new behavior. And with UASTC I don't think it'll happen, it's just a completely separate "product" from this ETC-based compression, not affecting it in any way, so it'll be implemented as such.

**Comment by Squareys** [comment]
> I don't think this counts as code duplication because you have to do this GL-dialect-specific branching in any case anyway

Alright, in that case I will hardcode the CompressedPixelFormat into that already existing format-check branching!
Thank you for explaining this in such detail 🙏
